language: python
python:
  - "3.7"
# command to install dependencies
install:
  - pip install -r info/requirements.txt
# command to run tests
before_script: cd info/
script:
  - python server.py
env:
  - DB_DBNAME=watches
  - DB_HOST=localhost
  - DB_PASS=DB_PASS
  - DB_USER=DB_USER
  - DB_PORT=3306
  - DB_DBNAME=DB_DBNAME
  - HTTP_USER=HTTP_USER
  - HTTP_PASS=HTTP_PASS
