
version: '3.2'

services:
    db:
        image: mysql:5.7
        container_name: db
        restart: always
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: watches
            MYSQL_DATABASE: watches
            MYSQL_USER: watches
            MYSQL_PASSWORD: watches
        volumes:
            - /var/lib/mysql
            - ~/Desktop/cloudcomputing-2021-assignments/project/misc:/docker-entrypoint-initdb.d

    phpmyadmin:
        depends_on:
            - db
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
            - '80:80'
        environment:
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: watches
            PMA_PASSWORD: watches

    app:
        depends_on:
            - db
        build: .
        container_name: info-service-v1
        restart: always
        ports:
            - '1080:1080'
        environment:
            DB_HOST: db
            DB_PORT: 3306
            DB_DBNAME: watches
            DB_USER: watches
            DB_PASS: watches
            HTTP_USER: cloud
            HTTP_PASS: computing